/*
 * IMPORTANT!
 * This file has been automatically generated,
 * in order to update its content execute "npm run update"
 */
module.exports = {
  extends: require.resolve('./base'),
  rules: {
    'vue-enhance/multi-word-component-names': 'error',
    'vue-enhance/no-arrow-functions-in-watch': 'error',
    'vue-enhance/no-async-in-computed-properties': 'error',
    'vue-enhance/no-child-content': 'error',
    'vue-enhance/no-computed-properties-in-data': 'error',
    'vue-enhance/no-custom-modifiers-on-v-model': 'error',
    'vue-enhance/no-dupe-keys': 'error',
    'vue-enhance/no-dupe-v-else-if': 'error',
    'vue-enhance/no-duplicate-attributes': 'error',
    'vue-enhance/no-export-in-script-setup': 'error',
    'vue-enhance/no-multiple-template-root': 'error',
    'vue-enhance/no-mutating-props': 'error',
    'vue-enhance/no-parsing-error': 'error',
    'vue-enhance/no-ref-as-operand': 'error',
    'vue-enhance/no-reserved-component-names': 'error',
    'vue-enhance/no-reserved-keys': 'error',
    'vue-enhance/no-reserved-props': [
      'error',
      {
        vueVersion: 2
      }
    ],
    'vue-enhance/no-setup-props-destructure': 'error',
    'vue-enhance/no-shared-component-data': 'error',
    'vue-enhance/no-side-effects-in-computed-properties': 'error',
    'vue-enhance/no-template-key': 'error',
    'vue-enhance/no-textarea-mustache': 'error',
    'vue-enhance/no-unused-components': 'error',
    'vue-enhance/no-unused-vars': 'error',
    'vue-enhance/no-use-computed-property-like-method': 'error',
    'vue-enhance/no-use-v-if-with-v-for': 'error',
    'vue-enhance/no-useless-template-attributes': 'error',
    'vue-enhance/no-v-for-template-key': 'error',
    'vue-enhance/no-v-model-argument': 'error',
    'vue-enhance/no-v-text-v-html-on-component': 'error',
    'vue-enhance/require-component-is': 'error',
    'vue-enhance/require-prop-type-constructor': 'error',
    'vue-enhance/require-render-return': 'error',
    'vue-enhance/require-v-for-key': 'error',
    'vue-enhance/require-valid-default-prop': 'error',
    'vue-enhance/return-in-computed-property': 'error',
    'vue-enhance/return-in-emits-validator': 'error',
    'vue-enhance/use-v-on-exact': 'error',
    'vue-enhance/valid-attribute-name': 'error',
    'vue-enhance/valid-define-emits': 'error',
    'vue-enhance/valid-define-props': 'error',
    'vue-enhance/valid-model-definition': 'error',
    'vue-enhance/valid-next-tick': 'error',
    'vue-enhance/valid-template-root': 'error',
    'vue-enhance/valid-v-bind-sync': 'error',
    'vue-enhance/valid-v-bind': 'error',
    'vue-enhance/valid-v-cloak': 'error',
    'vue-enhance/valid-v-else-if': 'error',
    'vue-enhance/valid-v-else': 'error',
    'vue-enhance/valid-v-for': 'error',
    'vue-enhance/valid-v-html': 'error',
    'vue-enhance/valid-v-if': 'error',
    'vue-enhance/valid-v-model': 'error',
    'vue-enhance/valid-v-on': 'error',
    'vue-enhance/valid-v-once': 'error',
    'vue-enhance/valid-v-pre': 'error',
    'vue-enhance/valid-v-show': 'error',
    'vue-enhance/valid-v-slot': 'error',
    'vue-enhance/valid-v-text': 'error'
  }
}
